version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t $AWS_ECR_ENDPOINT/example-app:latest -f docker/Dockerfile .
      - run:
          name: Install awscli
          command: |
            apk add --no-cache py-pip sudo
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Push docker image
          command: |
            eval "$(aws ecr get-login --no-include-email)"
            docker push $AWS_ECR_ENDPOINT/example-app:latest

  deploy-production:
    docker:
      - image: $AWS_ECR_ENDPOINT/universe/deploy:latest
    steps:
      - run:
          name: deploy to ecs
          command: |
            ecs-deploy --enable-rollback -c example_ecs_cluster -n example_ecs_service -i $AWS_ECR_ENDPOINT/example-app:latest -t 900


workflows:
  version: 2
  build-deploy:
    jobs:
      - build: { context: aws }
      - deploy-production: { requires: [build], filters: { branches: { only: [master] } }, context: aws }
